### ISSUE TITLE
main.jsbundle: No such file or directory

### ISSUE THREAD

**Issue by christopherstott** [rkho/product-kitty#126]
I'm trying to build in xcode 6.4, but I get this error (main.jsbundle: No such file or directory). Should the file be in git somewhere? or generated?

Thanks!

**Comment by danielbogart** [comment]
run `react-native bundle` in terminal from your project's root director

**Comment by rkho** [comment]
Apologies for the super late response on my end, @danielbogart is be correct. I'm going to close this issue, but if it comes up again please re-open it.
